env:
  browser: true
  es2021: true
extends: 
- airbnb
- plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/prefer-default-export: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  comma-dangle: 'off'
  object-curly-spacing: 'off'
  prefer-const: 'error'
  react/react-in-jsx-scope: 'off'
  react/jsx-props-no-spreading:  'off'
  react/jsx-no-constructed-context-values: 'warn'
  indent: 'off'
  require-jsdoc: 'off'
  react/prop-types: 'off'
  no-console: 'warn'
  no-use-before-define: 'off'
  no-underscore-dangle: 'off'
