arrowParens: always
bracketSpacing: true
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
insertPragma: false
requirePragma: false
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false