env:
  browser: true
  es2021: true
extends: 
- airbnb
- plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/prefer-default-export: 'off'
  comma-dangle: 'off'
  object-curly-spacing: 'off'
  prefer-const: error
  react/react-in-jsx-scope: 'off'
  indent: 'off'
  require-jsdoc: warn
  react/prop-types: warn
  guard-for-in: 'off'
  max-len: warn
