env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/prefer-default-export: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  comma-dangle: 'off'
  object-curly-spacing: 'off'
  prefer-const: 'error'
  prefer-destructuring: 'off'
  indent: 'off'
  require-jsdoc: 'off'
  no-console: 'warn'
  no-use-before-define: 'off'
  no-underscore-dangle: 'off'
